services:

  dev:
    image: 16nsk/devcontainers
    command: sleep infinity
    volumes:
      - projects:/projects
    ports:
      - "${BACKEND_PORT:-8000}:8000"
      - "${FRONTEND_PORT:-3000}:3000"

  # mariadb:
  #   image: mariadb:10.6
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=developer
  #     - MYSQL_USER=developer
  #     - MYSQL_PASSWORD=developer
  #   volumes:
  #     - mariadb:/var/lib/mysql
  #   ports:
  #     - "${FORWARD_DB_PORT:-3306}:3306"

  # postgres:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_PASSWORD=developer
  #     - POSTGRES_USER=developer
  #     - POSTGRES_DB=developer
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   ports:
  #     - "${FORWARD_DB_PORT:-5432}:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

  # elasticsearch:
  #   image: elasticsearch:8.4.3
  #   volumes:
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTIC_PASSWORD=elastic
  #     - xpack.security.enabled=false
  #     - xpack.security.transport.ssl.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #   mem_limit: 1073741824
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  
  # kibana:
  #   image: kibana:8.4.3
  #   volumes:
  #     - kibana:/usr/share/kibana/data
  #   ports:
  #     - ${KIBANA_PORT:-5601}:5601
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  # redis:
  #   image: redis:6-alpine
  #   volumes:
  #     - redis:/data
  #   command: redis-server --appendonly yes

  # mailhog:
  #   image: 16nsk/mailhog
  #   ports:
  #     - "${FORWARD_MAILHOG_PORT:-8025}:8025"

  # adminer:
  #   image: adminer
  #   ports:
  #     - "${FORWARD_ADMINER_PORT:-8080}:8080"

volumes:
  projects:
  # mariadb:
  # postgres:
  # redis:
  # elasticsearch:
