name: buildx-8.1-18-debian

on:
  schedule:
    - cron:  '11 5 * * 4'
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -  
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -  
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          cat <<'EOF' > docker-bake.hcl
          group "default" {
              targets = [
                  "default"
              ]
          }

          target "default" {
              context="."
              dockerfile="Dockerfile"
              platforms = [
                  "linux/amd64",
                  "linux/arm64"
              ]
              tags = [
                "16nsk/devcontainers:8.1-18-debian"
              ]
              args = {
                PHP_VERSION="8.1",
                NODE_VERSION="18",
                IMAGE="debian",
                DISTRO="debian",
                VERSION="bullseye"
              }
          }
          EOF
      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          files: docker-bake.hcl
